export const errors = {
  'getter-return': ['error', { allowImplicit: true }],
  'no-await-in-loop': 'error',
  'no-cond-assign': ['error', 'always'],
  'no-console': 'warn',
  'no-constant-binary-expression': 'error',
  'no-constant-condition': 'warn',
  'no-empty-character-class': 'error',
  'no-extra-parens': ['error', 'all', { nestedBinaryExpressions: false }],
  'no-extra-semi': 'error',
  'no-inner-declarations': 'error',
  'no-invalid-regexp': 'error',
  'no-new-native-nonconstructor': 'error',
  'no-promise-executor-return': 'error',
  'no-template-curly-in-string': 'error',
  'no-unreachable-loop': [
    'error', {
      ignore: [],
    },
  ],
  'no-unsafe-optional-chaining': ['error', { disallowArithmeticOperators: true }],
  'no-useless-backreference': 'error',
  'require-atomic-updates': 'off',
  'valid-typeof': ['error', { requireStringLiterals: true }],
};
