name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@egs33'

      - name: Install dependencies
        run: pnpm install

      - name: lint
        run: pnpm lint
